# Generated by Django 3.1.5 on 2021-01-17 07:00

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('otp_type', models.IntegerField(choices=[(0, 'Class')], default=0, validators=[djchoices.choices.ChoicesValidator({0: 'Class'})])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
