# Generated by Django 3.1.5 on 2021-01-17 07:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_sessions', models.PositiveIntegerField()),
                ('number_of_seats', models.PositiveIntegerField()),
                ('seats_booked', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Upcoming'), (1, 'Ongoing'), (2, 'Completed')], default=0, validators=[djchoices.choices.ChoicesValidator({0: 'Upcoming', 1: 'Ongoing', 2: 'Completed'})])),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ClassReserved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Cancelled')], default=0, validators=[djchoices.choices.ChoicesValidator({0: 'Pending', 1: 'Confirmed', 2: 'Cancelled'})])),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reserved_class_id', to='online_class.class')),
            ],
        ),
        migrations.CreateModel(
            name='ClassBooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_booked_class_id', to='online_class.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_type', to='online_class.classtype'),
        ),
    ]
