# Generated by Django 3.1.5 on 2021-01-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtype',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
