# Generated by Django 3.1.5 on 2021-01-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_class', '0002_auto_20210117_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
